import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {RectAreaLightUniformsLib} from 'three/examples/jsm/lights/RectAreaLightUniformsLib.js';
import {buildEnvironment, type EnvironmentKind, type EnvironmentResult} from '../environments/EnvironmentScene';
import {accumulatedDistances,type Trajectory,type CrowdManifest} from '../crowd/CrowdRenderer';
import {gpuPositionParity} from '../crowd/CrowdParity';
import {DemoCrowdRenderer} from './DemoCrowdRenderer';
const el=(id:string)=>document.getElementById(id)!;
const params=new URLSearchParams(location.search),moduleStart=performance.now();
const names={crossing:'One hundred stories',city:'Every window, a life',station:'Before the last train'};
let kind=(params.get('scene')||'crossing') as EnvironmentKind;if(!names[kind])kind='crossing';
const countControl=el('count') as HTMLSelectElement;countControl.value=params.get('count')||'112';
const actorControl=el('actor') as HTMLSelectElement,seek=el('seek') as HTMLInputElement;
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.prepend(renderer.domElement);
RectAreaLightUniformsLib.init();const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.12,700),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.88;controls.minDistance=1;controls.maxDistance=220;
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.03);scene.environment=environment.texture;scene.environmentIntensity=.35;room.dispose();pmrem.dispose();
const sky=new THREE.Mesh(new THREE.SphereGeometry(450,24,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#3484c3')},horizon:{value:new THREE.Color('#edd2b6')}},vertexShader:'varying vec3 vWorld;void main(){vWorld=(modelMatrix*vec4(position,1.0)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 horizon;varying vec3 vWorld;void main(){float h=pow(max(normalize(vWorld).y,0.0),0.45);gl_FragColor=vec4(mix(horizon,top,h),1.0);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'}));scene.add(sky);
const signals:THREE.MeshStandardMaterial[]=[];
let world:EnvironmentResult,lights=new THREE.Group(),crowd:DemoCrowdRenderer,trajectory:Trajectory,distances:number[][],manifest:CrowdManifest,affine:Float32Array;
let time=0,playing=true,director=true,following=false,selectedShot=-1,selectedActor=0,loading=false,last=performance.now(),loadMs=0,payloadBytes=0,initialReadyMs=0,status='';
let latestFps=0,frameCount=0,frameTime=0;const hashes:Record<string,{sha256:string;bytes:number}>={};let parity:ReturnType<typeof gpuPositionParity>;
async function bytes(url:string){const r=await fetch(url);if(!r.ok)throw new Error(`Cannot load ${url}: ${r.status}`);const b=await r.arrayBuffer();payloadBytes+=b.byteLength;const h=await crypto.subtle.digest('SHA-256',b);hashes[url]={bytes:b.byteLength,sha256:Array.from(new Uint8Array(h),v=>v.toString(16).padStart(2,'0')).join('')};return b;}
async function json(url:string){return JSON.parse(new TextDecoder().decode(await bytes(url)));}
const actorData=()=>trajectory?.agents[selectedActor] as any;
const events=()=>((trajectory as any)?.events||[]) as any[];
function currentFrame(){return Math.min(trajectory.frames.length-1,Math.max(0,Math.floor(time/trajectory.dt)));}
function rootAt(i:number){const f=Math.min(trajectory.frames.length-2,currentFrame()),a=trajectory.frames[f],b=trajectory.frames[f+1],q=THREE.MathUtils.clamp((time-a.t)/trajectory.dt,0,1);const pa=a.people[i] as number[],pb=b.people[i] as number[];return new THREE.Vector3(THREE.MathUtils.lerp(pa[0],pb[0],q),THREE.MathUtils.lerp(pa[8]||0,pb[8]||0,q),THREE.MathUtils.lerp(pa[1],pb[1],q));}
function shot(i:number){if(!world)return;selectedShot=i;following=false;const s=world.cameras[i];camera.position.fromArray(s.position);camera.fov=s.fov||55;camera.updateProjectionMatrix();controls.target.fromArray(s.target);controls.update();document.querySelectorAll('[data-shot]').forEach((b,n)=>b.classList.toggle('active',n===i));}
// Crowd film cameras keep street-level people in frame and avoid the signal pole.
function frameCrowdCameras(){
 if(kind==='crossing'){
  Object.assign(world.cameras[0],{position:[3,11,33],target:[0,1,-2],fov:58});
  Object.assign(world.cameras[1],{position:[10,1.85,15.5],target:[-9,1.1,-10],fov:66});
  Object.assign(world.cameras[2],{position:[0,1.8,3],target:[-14,1.2,-15],fov:71});
  Object.assign(world.cameras[3],{position:[1,41,9],target:[0,0,0],fov:52});
  world.cameras[4].target[1]=1.4;world.cameras[5].target[1]=1.5;
 }else if(kind==='city'){
  world.cameras[0].target[1]=1.8;world.cameras[4].target[1]=1.3;Object.assign(world.cameras[2],{position:[-26.8,1.65,-18.3],target:[-29,1.35,-23],fov:76});
 }else{
  Object.assign(world.cameras[0],{position:[33,17,31],target:[0,2,-19],fov:59});
  world.cameras[1].target[1]=1.4;world.cameras[2].target[1]=1.5;world.cameras[3].target[1]=1.5;
 }
}
function releaseWorld(){if(!world)return;const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>(),textures=new Set<THREE.Texture>();world.group.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)geometries.add(m.geometry);if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>materials.add(x));});for(const m of materials){for(const v of Object.values(m))if(v instanceof THREE.Texture)textures.add(v);m.dispose();}geometries.forEach(g=>g.dispose());textures.forEach(t=>t.dispose());scene.remove(world.group);lights.traverse(o=>{if(o instanceof THREE.DirectionalLight)o.shadow.dispose();});scene.remove(lights);if(crowd){scene.remove(crowd.group);crowd.dispose();}}
function lighting(){const l=world.lighting;scene.background=new THREE.Color(l.background);scene.fog=new THREE.Fog(l.background,l.fogNear,l.fogFar);renderer.toneMappingExposure=l.exposure;sky.material.uniforms.top.value.set(kind==='station'?'#404782':'#3484c3');sky.material.uniforms.horizon.value.set(kind==='station'?'#dfa984':'#edd2b6');lights=new THREE.Group();lights.add(new THREE.HemisphereLight('#c6d9ec','#84755e',kind==='station'?.48:l.ambientIntensity));const sun=new THREE.DirectionalLight(l.sunColor,kind==='station'?.7:l.sunIntensity);sun.position.fromArray(l.sun);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-85,right:85,top:85,bottom:-85,near:.5,far:300});sun.shadow.normalBias=.12;sun.shadow.bias=-.0001;lights.add(sun);if(kind==='station'){for(const x of [-21,0,21]){const light=new THREE.RectAreaLight('#ffd39a',5,18,12);light.position.set(x,5.95,-23);light.lookAt(x,0,-23);lights.add(light);}for(const x of [-25,0,25]){const light=new THREE.RectAreaLight('#ffe0b5',5,19,18);light.position.set(x,10.5,-46);light.lookAt(x,0,-46);lights.add(light);}}scene.add(lights);}
function busy(on:boolean){for(const b of document.querySelectorAll('button,select'))(b as HTMLButtonElement).disabled=on;seek.disabled=on;}
async function load(k:EnvironmentKind,count:number){if(loading||measurement)return;loading=true;busy(true);status='Loading saved tasks and reviewed motion…';const began=performance.now();try{const next=await json(`/review/crowd-demos/${k}-${count}.json`);if(next.agents.length!==count||next.frames.length<2)throw new Error('Invalid saved crowd population');releaseWorld();kind=k;trajectory=next;distances=accumulatedDistances(trajectory);world=buildEnvironment(k);frameCrowdCameras();scene.add(world.group);signals.length=0;world.group.traverse(o=>{const m=(o as THREE.Mesh).material;if(m)(Array.isArray(m)?m:[m]).forEach(mat=>{if(mat.userData.pedestrianSignal)signals.push(mat as THREE.MeshStandardMaterial);});});lighting();crowd=new DemoCrowdRenderer(manifest,affine,count);scene.add(crowd.group);time=0;selectedActor=0;playing=true;following=false;selectedShot=-1;seek.max=String(trajectory.duration);el('play').textContent='Pause';el('title').textContent=names[k];el('description').textContent=k==='crossing'?'A compact crossing, staggered arrivals and small encounters. Each person has a saved task sequence.':k==='city'?'Sidewalk errands, shop visits and a coordinated courtyard flashmob. Follow a person to see their task.':'Passengers, kiosk visits and meetings under warm concourse lights.';el('population').textContent=`${count} people · saved ${trajectory.duration}s take`;el('flashmob').hidden=!events().some(e=>e.kind==='flashmob');
 document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('active',(b as HTMLElement).dataset.scene===k));
 actorControl.replaceChildren(...trajectory.agents.map((a:any,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=`${String(a.id).padStart(3,'0')} · ${a.role||a.personality||a.task||a.gait}`;return o;}));
 el('shots').replaceChildren(...world.cameras.map((s,i)=>{const b=document.createElement('button');b.dataset.shot=String(i);b.textContent=`${String(i+1).padStart(2,'0')} · ${s.label}`;b.onclick=()=>{director=false;shot(i);};return b;}));
 shot(params.get('camera')==='overhead'?world.cameras.findIndex(c=>c.id==='overhead'):params.get('camera')==='street'?1:0);if(params.has('camera'))director=false;await renderer.compileAsync(scene,camera);crowd.update(trajectory,0,distances);const initialShot=selectedShot;for(let i=0;i<world.cameras.length;i++){shot(i);renderer.render(scene,camera);}shot(initialShot);renderer.render(scene,camera);renderer.getContext().finish();loadMs=performance.now()-began;el('profile').textContent=`Profile ${Number(params.get('duration')||trajectory.duration)}s`;status=`Saved tasks ready · ${(loadMs/1000).toFixed(2)}s scene load`;last=performance.now();}finally{loading=false;busy(false);}}
function fail(e:unknown){el('error').textContent=String(e);console.error(e);busy(false);loading=false;}
async function save(route:string,name:string,body:BodyInit,contentType?:string){const r=await fetch('/__demo/'+route+'?name='+name,{method:'POST',body,headers:contentType?{'Content-Type':contentType}:undefined});if(!r.ok)throw new Error(await r.text());return (await r.json()).saved as string;}
async function still(){renderer.render(scene,camera);const blob=await new Promise<Blob>((resolve,reject)=>renderer.domElement.toBlob(b=>b?resolve(b):reject(new Error('Capture failed')),'image/png'));const name=`${kind}-${crowd.count}-${selectedShot}-${Math.round(time)}`;const saved=await save('still',name,blob);await save('report',name,JSON.stringify({scene:kind,count:crowd.count,time,camera:{position:camera.position.toArray(),target:controls.target.toArray(),fov:camera.fov},selectedActor,shot:selectedShot}),'application/json');status='Saved '+saved;}
function percentile(values:number[]){const a=[...values].sort((a,b)=>a-b);return a.length?{median:a[Math.floor(a.length*.5)],p95:a[Math.min(a.length-1,Math.floor(a.length*.95))],p99:a[Math.min(a.length-1,Math.floor(a.length*.99))],max:a[a.length-1],samples:a.length}:null;}
type Measurement={start:number;end:number;dt:number[];cpu:number[];render:number[];heap:number[];gpu:number[];hidden:number;slow:{time:number;frameMs:number;shot:number}[];capture:boolean};let measurement:Measurement|null=null;let recorder:MediaRecorder|null=null,chunks:BlobPart[]=[];
const gl=renderer.getContext() as WebGL2RenderingContext,timer=gl.getExtension('EXT_disjoint_timer_query_webgl2');const pending:{query:WebGLQuery;owner:Measurement}[]=[];
function device(){const ext=gl.getExtension('WEBGL_debug_renderer_info');return {userAgent:navigator.userAgent,gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),resolution:[renderer.domElement.width,renderer.domElement.height],pixelRatio:renderer.getPixelRatio(),hardwareConcurrency:navigator.hardwareConcurrency};}
async function beginProfile(capture=false){if(measurement||loading)return;time=0;playing=true;el('play').textContent='Pause';last=performance.now();busy(true);if(capture){chunks=[];const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8'].find(x=>MediaRecorder.isTypeSupported(x));recorder=new MediaRecorder(renderer.domElement.captureStream(30),{mimeType:mime,videoBitsPerSecond:9_000_000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.start(1000);}const duration=capture?trajectory.duration:Number(params.get('duration')||trajectory.duration);measurement={start:performance.now(),end:performance.now()+duration*1000,dt:[],cpu:[],render:[],heap:[],gpu:[],hidden:0,slow:[],capture};status=`Measuring ${duration}s${capture?' and recording':''}…`;}
async function endProfile(){const m=measurement;if(!m)return;measurement=null;const duration=(performance.now()-m.start)/1000;const name=`${kind}-${crowd.count}-${director?'director':following?'follow':'view'+selectedShot}`;const report={schema:'stagezero.saved-crowd-profile.v1',scene:kind,count:crowd.count,durationWallSeconds:duration,sustainedFps:m.dt.length/duration,frameMs:percentile(m.dt),animationCpuMs:percentile(m.cpu),renderSubmissionCpuMs:percentile(m.render),gpuMs:percentile(m.gpu),heapBytes:percentile(m.heap),hiddenFrames:m.hidden,slowFrames:m.slow,validForegroundRun:m.hidden===0,loadMs,loadScope:'Scene data fetch, parse, geometry init and first render; excludes initial JS navigation. Module-to-ready recorded separately.',moduleToReadyMs:initialReadyMs,payloadBytes,inputHashes:hashes,device:device(),rendererMemory:renderer.info.memory,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,actorTriangles:crowd.triangleCount,positionParity:parity,trajectoryMetrics:(trajectory as any).metrics,capture:m.capture,notes:['Saved offline trajectories, not live navigation decisions','GPU affine shared Xbot mesh; root-discs do not certify full mesh collision','Heap excludes GPU and total process memory','Background shadow maps; animated people use contact blobs, no SSAO override']};try{const file=await save('report',name,JSON.stringify(report,null,2),'application/json');if(recorder){const r=recorder;await new Promise<void>((resolve,reject)=>{r.onstop=async()=>{try{await save('video',name,new Blob(chunks,{type:'video/webm'}));r.stream.getTracks().forEach(t=>t.stop());resolve();}catch(e){reject(e);}};r.stop();});recorder=null;}status=`Saved ${file}\n${report.sustainedFps.toFixed(1)} FPS · p95 ${report.frameMs?.p95.toFixed(1)}ms`;el('profile').textContent='Profile saved';}catch(e){fail(e);}finally{busy(false);}}
function inspect(){if(!trajectory)return;const a=actorData(),p=trajectory.frames[currentFrame()].people[selectedActor];const schedules=a.schedule||a.tasks||[];const task=schedules.find((s:any)=>time>=(s.start??s.start_s??0)&&time<(s.end??s.end_s??Infinity));const states=(trajectory as any).state_names||(trajectory as any).states||{};el('task').textContent=`${a.role||a.personality||'Pedestrian'} · ${task?.label||task?.task||states[p[4]]||'Following assigned route'}`;el('intent').textContent=a.intent||a.prompt||a.personality||'Continue to the next destination after this task.';}
function meetingCamera(e:any){const a=e.anchor_xz||e.anchor||[0,0];const toward=new THREE.Vector3(-a[0],0,-a[1]).normalize();camera.fov=52;camera.updateProjectionMatrix();camera.position.set(a[0]+toward.x*5.5,2.65,a[1]+toward.z*5.5);controls.target.set(a[0],1.05,a[1]);selectedShot=-2;}
function directorCamera(){
 const dance=events().find(e=>e.kind==='flashmob'&&time>=(e.dance_start_s??40)&&time<(e.dance_end_s??65));
 if(dance){const a=dance.anchor_xz||dance.center_xz||[-48,-54],t=time-(dance.dance_start_s??40);camera.fov=t<8?62:t<18?65:54;camera.updateProjectionMatrix();if(t<8)camera.position.set(a[0],7,a[1]+14);else if(t<18)camera.position.set(a[0]-10,3.2,a[1]+7);else camera.position.set(a[0],22,a[1]+2);controls.target.set(a[0],t<18?1:0,a[1]);selectedShot=-3;return;}
 const e=events().find(x=>x.actor_ids?.length===2&&time>=(x.start_s??x.start)&&time<=(x.end_s??x.end));if(e){meetingCamera(e);return;}const next=kind==='city'?(time<12?0:time<33?1:time<78?2:time<90?3:time<105?4:5):Math.min(world.cameras.length-1,Math.floor(time/(trajectory.duration/world.cameras.length)));if(next!==selectedShot)shot(next);const s=world.cameras[selectedShot];const q=(time%(trajectory.duration/world.cameras.length))/(trajectory.duration/world.cameras.length);camera.position.set(s.position[0]+Math.sin(q*Math.PI)*1,s.position[1],s.position[2]+Math.sin(q*Math.PI)*.4);}

function animate(now:number){requestAnimationFrame(animate);const dt=now-last;last=now;if(!crowd||loading)return;if(playing){time=Math.min(trajectory.duration,time+dt/1000);if(time>=trajectory.duration){playing=false;el('play').textContent='Replay';}}if(director)directorCamera();if(following){const p=rootAt(selectedActor);camera.position.lerp(p.clone().add(new THREE.Vector3(4,2.7,5)),.08);controls.target.lerp(p.clone().add(new THREE.Vector3(0,1,0)),.15);}controls.update();camera.position.y=Math.max(.45,camera.position.y);const began=performance.now();crowd.update(trajectory,time,distances);const update=performance.now()-began;
 while(timer&&pending.length&&gl.getQueryParameter(pending[0].query,gl.QUERY_RESULT_AVAILABLE)){const q=pending.shift()!;if(!gl.getParameter(timer.GPU_DISJOINT_EXT))q.owner.gpu.push(gl.getQueryParameter(q.query,gl.QUERY_RESULT)/1e6);gl.deleteQuery(q.query);}let query:WebGLQuery|null=null;if(timer&&measurement&&pending.length<8){query=gl.createQuery();if(query)gl.beginQuery(timer.TIME_ELAPSED_EXT,query);}const renderStart=performance.now();renderer.render(scene,camera);const renderMs=performance.now()-renderStart;if(query&&timer&&measurement){gl.endQuery(timer.TIME_ELAPSED_EXT);pending.push({query,owner:measurement});}
 if(measurement){measurement.dt.push(dt);if(dt>50)measurement.slow.push({time,frameMs:dt,shot:selectedShot});measurement.cpu.push(update);measurement.render.push(renderMs);const heap=(performance as any).memory?.usedJSHeapSize;if(heap)measurement.heap.push(heap);if(document.visibilityState!=='visible')measurement.hidden++;if(now>=measurement.end)void endProfile();}
 if(kind==='crossing'){const phase=time%54,color=phase<10?'#f35349':phase<46?'#65e7a1':'#efb94f';for(const m of signals){m.color.set(color);m.emissive.set(color);}}
 frameCount++;frameTime+=dt;if(frameTime>=500){latestFps=frameCount*1000/frameTime;frameCount=0;frameTime=0;seek.value=String(time);el('clock').textContent=`${time.toFixed(1)} / ${trajectory.duration}s · ${crowd.count} people${kind==='crossing'?(time%54<10?' · WAIT':time%54<46?' · CROSS':' · CLEAR'):''}${playing?'':' · paused'}`;el('status').textContent=measurement?`Measuring · ${Math.max(0,(measurement.end-now)/1000).toFixed(0)}s remaining · ${latestFps.toFixed(0)} FPS`:`${status}\n${latestFps.toFixed(0)} FPS · ${renderer.info.render.calls} draws`;inspect();}}
el('play').onclick=()=>{if(time>=trajectory.duration)time=0;playing=!playing;el('play').textContent=playing?'Pause':'Play';};el('restart').onclick=()=>{time=0;playing=true;el('play').textContent='Pause';};el('director').onclick=()=>{director=!director;following=false;selectedShot=-1;el('director').classList.toggle('active',director);};seek.oninput=()=>{time=Number(seek.value);playing=false;el('play').textContent='Play';inspect();};actorControl.onchange=()=>{selectedActor=Number(actorControl.value);inspect();};el('follow').onclick=()=>{following=!following;director=false;el('follow').classList.toggle('active',following);};el('meeting').onclick=()=>{const e=events().find(x=>x.actor_ids?.length===2);if(!e){status='No reviewed meeting in this preset';return;}selectedActor=trajectory.agents.findIndex(a=>a.id===e.actor_ids[0]);actorControl.value=String(selectedActor);time=(e.start_s??e.start)+1;following=false;director=false;playing=true;meetingCamera(e);inspect();};el('flashmob').onclick=()=>{const e=events().find(x=>x.kind==='flashmob');if(!e)return;time=e.dance_start_s??40;selectedActor=trajectory.agents.findIndex(a=>a.id===e.actor_ids[0]);actorControl.value=String(selectedActor);following=false;director=true;playing=true;el('play').textContent='Pause';inspect();};el('profile').onclick=()=>beginProfile(false).catch(fail);el('record').onclick=()=>beginProfile(true).catch(fail);el('still').onclick=()=>still().catch(fail);countControl.onchange=()=>load(kind,Number(countControl.value)).catch(fail);document.querySelectorAll('[data-scene]').forEach(b=>(b as HTMLButtonElement).onclick=()=>load((b as HTMLElement).dataset.scene as EnvironmentKind,Number(countControl.value)).catch(fail));controls.addEventListener('start',()=>{director=false;following=false;});
renderer.domElement.addEventListener('click',e=>{if(measurement||!trajectory)return;let best=28,index=-1;for(let i=0;i<crowd.count;i++){const p=rootAt(i).add(new THREE.Vector3(0,1,0)).project(camera);if(p.z<-1||p.z>1)continue;const d=Math.hypot((p.x*.5+.5)*innerWidth-e.clientX,(-p.y*.5+.5)*innerHeight-e.clientY);if(d<best){best=d;index=i;}}if(index>=0){selectedActor=index;actorControl.value=String(index);inspect();}});
window.onresize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);};
async function init(){const url=params.get('assets')||'/review/crowd-demos/assets/manifest.json';manifest=await json(url);affine=new Float32Array(await bytes(new URL(manifest.affineUrl,new URL(url,location.href)).href));parity=gpuPositionParity(renderer,manifest,affine);if(!parity.passed)throw new Error('GPU position parity failed');await load(kind,Number(countControl.value));initialReadyMs=performance.now()-moduleStart;last=performance.now();requestAnimationFrame(animate);if(params.get('auto')==='profile'||params.get('auto')==='record')setTimeout(()=>beginProfile(params.get('auto')==='record').catch(fail),1500);}
init().catch(fail);
