import test from 'node:test';
import assert from 'node:assert/strict';
import { createMessageThrottle } from '../src/MessageThrottle.ts';
test('different GUI controls are not lost within one throttle interval', t => {
  t.mock.timers.enable({ apis: ['setTimeout'] });
  const out = [];
  const queue = createMessageThrottle(message => out.push(message), 15);
  t.after(() => queue.dispose());
  queue.send({type:'GuiUpdateMessage', uuid:'prompt', updates:{value:'walk'}});
  queue.send({type:'GuiUpdateMessage', uuid:'source', updates:{value:'Live ARDY'}});
  queue.send({type:'GuiUpdateMessage', uuid:'generate', updates:{value:true}});
  assert.deepEqual(out.map(m => m.uuid), ['prompt']);
  t.mock.timers.tick(15);
  assert.deepEqual(out.map(m => m.uuid), ['prompt','source','generate']);
});
test('trailing seek is sent, intermediate values coalesce, dispose cancels pending work', t => {
  t.mock.timers.enable({ apis: ['setTimeout'] });
  const out = [];
  const queue = createMessageThrottle(message => out.push(message), 15);
  t.after(() => queue.dispose());
  for (let i=0;i<10;i++) queue.send({type:'TimelineUpdateMessage',current_frame:i});
  assert.deepEqual(out.map(m => m.current_frame), [0]);
  t.mock.timers.tick(15);
  assert.deepEqual(out.map(m => m.current_frame), [0,9]);
  queue.send({type:'TimelineUpdateMessage',current_frame:10});
  assert.deepEqual(out.map(m => m.current_frame), [0,9]);
  queue.dispose();
  t.mock.timers.tick(30);
  assert.deepEqual(out.map(m => m.current_frame), [0,9]);
});
