import * as THREE from 'three';
import {gpuPositionParity} from './CrowdParity';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {CrowdRenderer,accumulatedDistances,benchmarkNative} from './CrowdRenderer';
import type {CrowdManifest,Trajectory} from './CrowdRenderer';
const params=new URLSearchParams(location.search),el=(id:string)=>document.getElementById(id)!;
const status=(text:string)=>el('status').textContent=text;
const start=performance.now();let payloadBytes=0;const inputHashes:Record<string,{sha256:string;bytes:number}>={};
async function hashInput(url:string,bytes:ArrayBuffer){const digest=await crypto.subtle.digest('SHA-256',bytes);inputHashes[url]={sha256:Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join(''),bytes:bytes.byteLength};}
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;document.body.prepend(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#b8cbd1');scene.fog=new THREE.Fog('#b8cbd1',65,150);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,220);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2-.015;
scene.add(new THREE.HemisphereLight('#e6f3ff','#666454',2.1));const sun=new THREE.DirectionalLight('#fff0d3',3);sun.position.set(-18,40,12);scene.add(sun);
const cameraMode=el('camera') as HTMLSelectElement;cameraMode.value=params.get('camera')||'street';
function setCamera(mode:string){if(mode==='overhead'){camera.position.set(0,44,15);controls.target.set(0,0,0);}else {camera.position.set(11,2.3,20);controls.target.set(0,1,0);}controls.update();}setCamera(cameraMode.value);
cameraMode.onchange=()=>setCamera(cameraMode.value);
window.onresize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);};
const countSelect=el('count') as HTMLSelectElement;countSelect.value=params.get('count')||'64';
(el('duration') as HTMLInputElement).value=params.get('duration')||'120';
const base=params.get('assets')||'/review/crowd-crossing/assets/manifest.json';
const absolute=(relative:string,baseUrl=base)=>new URL(relative,new URL(baseUrl,location.href)).href;
async function json(url:string){const r=await fetch(url);if(!r.ok)throw new Error(`${url}: ${r.status}`);const bytes=await r.arrayBuffer();payloadBytes+=bytes.byteLength;await hashInput(url,bytes);return JSON.parse(new TextDecoder().decode(bytes));}
const backgroundUrl=params.get('background')||absolute('crossing_scene.json');
let positionParity:ReturnType<typeof gpuPositionParity>|null=null;
let crowd:CrowdRenderer,manifest:CrowdManifest,affine:Float32Array,trajectory:Trajectory,distances:number[][];
let playing=true,busyNative=false,time=0,last=performance.now(),loadMs=0,frameCount=0,elapsedWall=0;
type Measurement={start:number;end:number;dt:number[];update:number[];render:number[];heap:number[];hidden:number;camera:string;capture:boolean;gpu:number[]};
let measurement:Measurement|null=null;
let recorder:MediaRecorder|null=null,chunks:BlobPart[]=[];
const evidence=params.get('evidence');let sequence=0;
async function sendReport(name:string,data:unknown){const text=JSON.stringify(data,null,2);el('result').textContent=text;(window as any).lastCrowdReport=data;if(evidence){const r=await fetch(`${evidence}/report?name=${encodeURIComponent(name)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:text});if(!r.ok)throw new Error(`Evidence write failed ${r.status}`);}else{const blob=new Blob([text],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.json';a.click();}}
function percentile(a:number[]){const s=[...a].sort((x,y)=>x-y);return s.length?{median:s[Math.floor(s.length*.5)],p95:s[Math.min(s.length-1,Math.floor(s.length*.95))],p99:s[Math.min(s.length-1,Math.floor(s.length*.99))],max:s[s.length-1],samples:s.length}:null;}
const gl=renderer.getContext() as WebGL2RenderingContext;const timer=gl.getExtension('EXT_disjoint_timer_query_webgl2');const pending:{q:WebGLQuery;owner:Measurement|null}[]=[];
function gpuBegin(){if(!timer||pending.length>8)return null;const q=gl.createQuery();if(q)gl.beginQuery(timer.TIME_ELAPSED_EXT,q);return q;}
function gpuEnd(q:WebGLQuery|null){if(q&&timer){gl.endQuery(timer.TIME_ELAPSED_EXT);pending.push({q,owner:measurement});}}
function gpuPoll(){if(!timer)return;while(pending.length&&gl.getQueryParameter(pending[0].q,gl.QUERY_RESULT_AVAILABLE)){const {q,owner}=pending.shift()!;if(!gl.getParameter(timer.GPU_DISJOINT_EXT)&&owner)owner.gpu.push(gl.getQueryParameter(q,gl.QUERY_RESULT)/1e6);gl.deleteQuery(q);}}
function device(){const debug=gl.getExtension('WEBGL_debug_renderer_info');return {userAgent:navigator.userAgent,platform:navigator.platform,hardwareConcurrency:navigator.hardwareConcurrency,deviceMemoryGiB:(navigator as any).deviceMemory||null,gpu:debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),resolution:[renderer.domElement.width,renderer.domElement.height],cssResolution:[innerWidth,innerHeight],pixelRatio:renderer.getPixelRatio()};}
async function beginCapture(){const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw new Error('WebM recording unsupported');chunks=[];recorder=new MediaRecorder(renderer.domElement.captureStream(30),{mimeType:mime,videoBitsPerSecond:7_000_000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.start(1000);}
async function finishCapture(name:string){const r=recorder;if(!r)return null;return new Promise<string>((resolve,reject)=>{r.onstop=async()=>{const blob=new Blob(chunks,{type:r.mimeType});try{if(evidence){const response=await fetch(`${evidence}/video?name=${encodeURIComponent(name+'.webm')}`,{method:'POST',headers:{'Content-Type':blob.type},body:blob});if(!response.ok)throw new Error('Video evidence upload failed');}else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.webm';a.click();}r.stream.getTracks().forEach(t=>t.stop());resolve(name+'.webm');}catch(e){reject(e);}};r.stop();recorder=null;});}
async function finishMeasurement(){const m=measurement;if(!m)return;measurement=null;setMeasuringControls(false);const name=`crowd-${crowd.count}-${m.camera}-${++sequence}-${Date.now()}`;const wall=(performance.now()-m.start)/1000;const report={schema:'stagezero.crowd.browser-profile.v1',createdAt:new Date().toISOString(),device:device(),actors:crowd.count,quality:'GPU affine, shared mesh, procedural contact blobs (not true shadows), DPR capped1.5',durationWallSeconds:wall,frames:m.dt.length,sustainedFps:m.dt.length/wall,frameMs:percentile(m.dt),updateCpuMs:percentile(m.update),renderSubmissionCpuMs:percentile(m.render),gpuMs:percentile(m.gpu),gpuTimingAvailable:!!timer,hiddenFrameCount:m.hidden,validForegroundRun:m.hidden===0,loadMs,payloadBytes,positionParity,payloadScope:'all bytes fetched on this page (fresh URL recommended per population)',inputHashes,heapBytes:percentile(m.heap),rendererMemory:renderer.info.memory,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,actorTriangles:crowd.triangleCount,camera:m.camera,trajectorySource:trajectoryUrl(crowd.count),motionSource:base,backgroundSource:backgroundUrl,liveCapture:m.capture,sceneEndTime:time,notes:['rAF includes real wall-clock browser scheduling; capture is MediaRecorder realtime, not deterministic frame export','Render CPU measures command submission; GPU timer may be unavailable','JS heap excludes GPU allocation and may require browser precise-memory flags','Procedural speed-driven idle blend; approximate affine normals; no skin geometry LOD']};status(`Profile complete: ${report.sustainedFps.toFixed(1)} fps\np95 ${report.frameMs?.p95.toFixed(1)} ms; hidden frames ${m.hidden}\nSaving evidence…`);try{await sendReport(name,report);if(m.capture)await finishCapture(name);status(`Saved ${name}\n${report.sustainedFps.toFixed(1)} fps · p95 ${report.frameMs?.p95.toFixed(1)} ms`);}catch(e){fail(e);}}
function setMeasuringControls(disabled:boolean){for(const id of ['count','camera','play','restart','native','profile','capture'])(el(id) as HTMLButtonElement).disabled=disabled;}
async function profile(capture=false){if(measurement||busyNative)return;const duration=Number((el('duration') as HTMLInputElement).value);time=0;playing=true;el('play').textContent='Pause';last=performance.now();setMeasuringControls(true);if(capture)await beginCapture();measurement={start:performance.now(),end:performance.now()+duration*1000,dt:[],update:[],render:[],heap:[],hidden:0,camera:cameraMode.value,capture,gpu:[]};status(`Measuring ${crowd.count} people · ${duration}s${capture?' · recording actual playback':''}`);}
function trajectoryUrl(count:number){return (params.get('trajectory')||'/review/crowd-crossing/trajectories-{count}.json').replace('{count}',String(count)).replace(/trajectories-\d+\.json/,`trajectories-${count}.json`);}
async function loadCount(count:number){trajectory=await json(trajectoryUrl(count));if(trajectory.agents.length<count)throw new Error('Trajectory population mismatch');distances=accumulatedDistances(trajectory);if(crowd){scene.remove(crowd.group);crowd.dispose();}crowd=new CrowdRenderer(manifest,affine,count);scene.add(crowd.group);crowd.update(trajectory,0,distances);time=0;status(`${count} pedestrians ready\n${Math.round(crowd.triangleCount).toLocaleString()} actor triangles`);}
countSelect.onchange=()=>{if(measurement){countSelect.value=String(crowd.count);return;}loadCount(Number(countSelect.value)).catch(fail);};
el('play').onclick=()=>{if(time>=trajectory.duration){status('Scene complete. Use Restart scene to play again.');return;}playing=!playing;el('play').textContent=playing?'Pause':'Play';};el('restart').onclick=()=>{time=0;playing=true;el('play').textContent='Pause';};el('profile').onclick=()=>profile().catch(fail);el('capture').onclick=()=>profile(true).catch(fail);
async function runNative(){if(measurement||busyNative)return;busyNative=true;status('Profiling unchanged native CPU functions at 16 / 32 / 64 / 100…');try{const result=await benchmarkNative(manifest,affine);await sendReport('native-cpu-baseline-'+Date.now(),result);status('Native CPU baseline saved');return result;}finally{busyNative=false;last=performance.now();}}
el('native').onclick=()=>runNative().catch(fail);
function fail(error:unknown){el('error').textContent=String(error);console.error(error);}
function animate(now:number){requestAnimationFrame(animate);const dt=now-last;last=now;if(!crowd||busyNative)return;if(playing){time=Math.min(time+dt/1000,trajectory.duration);if(time>=trajectory.duration){playing=false;el('play').textContent='Ended';}}
 if(cameraMode.value==='orbit'){const theta=time*.055;camera.position.set(Math.sin(theta)*26,8+Math.sin(theta*.3)*3,Math.cos(theta)*26);controls.target.set(0,1,0);}controls.update();
 const updateStart=performance.now();crowd.update(trajectory,time,distances);const updateMs=performance.now()-updateStart;gpuPoll();const q=measurement?gpuBegin():null;const renderStart=performance.now();renderer.render(scene,camera);const renderMs=performance.now()-renderStart;gpuEnd(q);
 if(measurement){measurement.dt.push(dt);measurement.update.push(updateMs);measurement.render.push(renderMs);if(document.visibilityState!=='visible')measurement.hidden++;const heap=(performance as any).memory?.usedJSHeapSize;if(heap)measurement.heap.push(heap);if(now>=measurement.end)void finishMeasurement();}
 frameCount++;elapsedWall+=dt;if(frameCount%20===0){const phase=time%60;el('clock').innerHTML=`<span class="light" style="background:${phase<15?'#e36e67':phase<53?'#6bd196':'#dfb354'}"></span>${phase<15?'PEDESTRIANS WAIT':phase<53?'CROSSING OPEN':'CLEAR CROSSING'} · ${time.toFixed(1)}s · ${crowd.count} people`;if(measurement)status(`Measuring ${crowd.count} people · ${Math.max(0,(measurement.end-now)/1000).toFixed(0)}s left\n${(frameCount*1000/elapsedWall).toFixed(1)} fps since load${measurement.capture?' · recording':''}`);}
}
async function init(){manifest=await json(base);const r=await fetch(absolute(manifest.affineUrl));if(!r.ok)throw new Error('Affine data missing');const bytes=await r.arrayBuffer();payloadBytes+=bytes.byteLength;await hashInput(absolute(manifest.affineUrl),bytes);affine=new Float32Array(bytes);if(manifest.totalFrames>gl.getParameter(gl.MAX_TEXTURE_SIZE))throw new Error('Animation texture exceeds GPU limit');const bg=await json(backgroundUrl);const groups=new Map<string,any[]>();for(const box of bg.boxes){const group=groups.get(box.color+'|'+(box.shape||'box'))||[];group.push(box);groups.set(box.color+'|'+(box.shape||'box'),group);}for(const [key,boxes] of groups){const [color,shape]=key.split('|');const geo=shape==='sphere'?new THREE.SphereGeometry(.5,12,8):shape==='cylinder'?new THREE.CylinderGeometry(.5,.5,1,12):new THREE.BoxGeometry(1,1,1);const mesh=new THREE.InstancedMesh(geo,new THREE.MeshStandardMaterial({color,roughness:.9}),boxes.length);const dummy=new THREE.Object3D();boxes.forEach((box,i)=>{dummy.position.fromArray(box.center);dummy.scale.fromArray(box.size);dummy.rotation.set(...(box.rotation||[0,box.yawRadians||0,0]) as [number,number,number]);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);});mesh.instanceMatrix.needsUpdate=true;scene.add(mesh);}if(params.get('auto')==='native'){loadMs=performance.now()-start;await runNative();return;}positionParity=gpuPositionParity(renderer,manifest,affine);if(!positionParity.passed)throw new Error('GPU position parity failed '+JSON.stringify(positionParity));await loadCount(Number(countSelect.value));renderer.compile(scene,camera);loadMs=performance.now()-start;(window as any).crowd={profile,benchmarkNative:runNative,device,loadCount,seek:(t:number)=>time=t,getState:()=>({time,count:crowd.count,loadMs,payloadBytes,measuring:!!measurement})};last=performance.now();requestAnimationFrame(animate);const auto=params.get('auto');if(auto==='native')await runNative();else if(auto==='profile')setTimeout(()=>profile(params.get('capture')==='1').catch(fail),1500);}
init().catch(fail);
