import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {EffectComposer} from 'three/examples/jsm/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/examples/jsm/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/examples/jsm/postprocessing/SSAOPass.js';
import {RectAreaLightUniformsLib} from 'three/examples/jsm/lights/RectAreaLightUniformsLib.js';
import {OutputPass} from 'three/examples/jsm/postprocessing/OutputPass.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {buildEnvironment} from './EnvironmentScene';
type Kind='crossing'|'city'|'station';
const el=(id:string)=>document.getElementById(id)!;
const captions:Record<Kind,{title:string;eyebrow:string;description:string}>={crossing:{title:'A thousand crossings',eyebrow:'01 / Tokyo-inspired scramble',description:'A broad crossing, layered shopfronts and streets that continue beyond the frame. Built for a future crowd with arrivals, departures and intersecting stories.'},city:{title:'Every window, a life',eyebrow:'02 / The connected city block',description:'From sidewalk to café, bookshop and quiet courtyard. A set for following different lives through shared streets and intimate interiors.'},station:{title:'Before the last train',eyebrow:'03 / Station plaza at dusk',description:'A glazed concourse, warm kiosks and an open arrival plaza. A future stage for reunions, missed connections and the evening rush.'}};
const params=new URLSearchParams(location.search);let kind=(params.get('scene')||'crossing') as Kind;if(!captions[kind])kind='crossing';
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.prepend(renderer.domElement);
RectAreaLightUniformsLib.init();const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.15,700);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.9;controls.minDistance=1;controls.maxDistance=220;
const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();const env=pmrem.fromScene(room,.03);scene.environment=env.texture;scene.environmentIntensity=.35;room.dispose();pmrem.dispose();
renderer.info.autoReset=false;const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,innerWidth,innerHeight);ao.kernelRadius=.65;ao.minDistance=.002;ao.maxDistance=.075;composer.addPass(ao);composer.addPass(new OutputPass());
const sky=new THREE.Mesh(new THREE.SphereGeometry(450,24,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#789fbf')},horizon:{value:new THREE.Color('#dfe5df')}},vertexShader:'varying vec3 vWorld;void main(){vWorld=(modelMatrix*vec4(position,1.0)).xyz;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform vec3 top;uniform vec3 horizon;varying vec3 vWorld;void main(){float h=pow(max(normalize(vWorld).y,0.0),0.45);gl_FragColor=vec4(mix(horizon,top,h),1.0);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'}));sky.name='Atmosphere';scene.add(sky);
let world:ReturnType<typeof buildEnvironment>;let lights=new THREE.Group();let selected=0,tour=false,tourStart=0,recording=false;let recorder:MediaRecorder|null=null;let chunks:BlobPart[]=[];let statusExtra='';let frames=0,lastPerf=performance.now(),fps=0;
function shot(index:number){selected=index%world.cameras.length;const s=world.cameras[selected];camera.position.fromArray(s.position);camera.fov=s.fov||45;camera.updateProjectionMatrix();ao.setSize(innerWidth,innerHeight);controls.target.fromArray(s.target);controls.update();document.querySelectorAll('[data-shot]').forEach((b,i)=>b.classList.toggle('active',i===selected));}
function disposeWorld(){if(!world)return;const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>(),textures=new Set<THREE.Texture>();world.group.traverse(o=>{const mesh=o as THREE.Mesh;if(mesh.geometry)geometries.add(mesh.geometry);if(mesh.material)(Array.isArray(mesh.material)?mesh.material:[mesh.material]).forEach(m=>materials.add(m));});materials.forEach(m=>{for(const v of Object.values(m))if(v instanceof THREE.Texture)textures.add(v);m.dispose();});geometries.forEach(g=>g.dispose());textures.forEach(t=>t.dispose());scene.remove(world.group);lights.traverse(o=>{if(o instanceof THREE.DirectionalLight)o.shadow.dispose();});scene.remove(lights);}
function load(k:Kind){if(recording)return;tour=false;el('tour').textContent='Play camera tour';disposeWorld();kind=k;world=buildEnvironment(k);scene.add(world.group);const l=world.lighting;scene.background=new THREE.Color(l.background);scene.fog=new THREE.Fog(l.background,l.fogNear,l.fogFar);renderer.toneMappingExposure=l.exposure;(sky.material.uniforms.top.value as THREE.Color).set(k==='station'?'#34465d':'#82a4bd');(sky.material.uniforms.horizon.value as THREE.Color).set(k==='station'?'#b5a08e':'#d5dbd5');lights=new THREE.Group();lights.add(new THREE.HemisphereLight('#c6d9ec','#84755e',k==='station'?.48:l.ambientIntensity));const sun=new THREE.DirectionalLight(l.sunColor,k==='station'?.7:l.sunIntensity);sun.position.fromArray(l.sun);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-90;sun.shadow.camera.right=90;sun.shadow.camera.top=90;sun.shadow.camera.bottom=-90;sun.shadow.camera.near=.5;sun.shadow.camera.far=300;sun.shadow.normalBias=.12;sun.shadow.bias=-.0001;lights.add(sun);if(k==='station'){for(const x of [-21,0,21]){const area=new THREE.RectAreaLight('#ffd39a',5,18,12);area.position.set(x,5.95,-23);area.lookAt(x,0,-23);lights.add(area);}for(const x of [-25,0,25]){const area=new THREE.RectAreaLight('#ffe0b5',5,19,18);area.position.set(x,10.5,-46);area.lookAt(x,0,-46);lights.add(area);}for(const x of [-22,22]){const light=new THREE.PointLight('#ffd2a0',28,12,2);light.position.set(x,2.5,6);lights.add(light);}}scene.add(lights);const text=captions[k];for(const id of ['title','eyebrow','description'] as const)el(id).textContent=text[id];document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('active',(b as HTMLElement).dataset.scene===k));el('shots').replaceChildren(...world.cameras.map((s,i)=>{const b=document.createElement('button');b.dataset.shot=String(i);const n=document.createElement('span');n.textContent=String(i+1).padStart(2,'0');b.append(n,s.label);b.onclick=()=>{if(recording)return;tour=false;el('tour').textContent='Play camera tour';shot(i);};return b;}));shot(Math.min(Number(params.get('view')||0),world.cameras.length-1));statusExtra='Background only · Crowd choreography awaits movement work';lastPerf=performance.now();}
function toggleTour(){if(recording)return;tour=!tour;el('tour').textContent=tour?'Stop camera tour':'Play camera tour';if(tour){tourStart=performance.now();shot(0);}}
async function saveStill(){renderer.info.reset();composer.render();const payload={schema:'stagezero.environment-still.v1',scene:kind,camera:world.cameras[selected],actualCamera:{position:camera.position.toArray(),target:controls.target.toArray(),fov:camera.fov},metadata:world.metadata,renderer:{width:innerWidth,height:innerHeight,pixelRatio:renderer.getPixelRatio(),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles},image:renderer.domElement.toDataURL('image/png')};const r=await fetch('/__environment/still?name='+kind+'-'+world.cameras[selected].id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());statusExtra='Saved '+(await r.json()).saved;}
async function recordTour(){if(recording)return;recording=true;chunks=[];shot(0);tour=true;tourStart=performance.now();el('record').textContent='Recording…';el('tour').textContent='Camera tour';const stream=renderer.domElement.captureStream(30);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8_000_000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());try{const r=await fetch('/__environment/video?name='+kind+'-camera-tour',{method:'POST',body:new Blob(chunks,{type:'video/webm'})});if(!r.ok)throw new Error(await r.text());statusExtra='Saved '+(await r.json()).saved;}catch(e){fail(e);}recording=false;el('record').textContent='Record tour';};recorder.start(1000);}
function fail(e:unknown){el('error').textContent=String(e);console.error(e);}
el('tour').onclick=toggleTour;el('still').onclick=()=>saveStill().catch(fail);el('record').onclick=()=>recordTour().catch(fail);document.querySelectorAll('[data-scene]').forEach(b=>(b as HTMLButtonElement).onclick=()=>{try{load((b as HTMLElement).dataset.scene as Kind);}catch(e){fail(e);}});controls.addEventListener('start',()=>{if(!recording){tour=false;el('tour').textContent='Play camera tour';}});
window.onresize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);};
function animate(now:number){requestAnimationFrame(animate);if(!world)return;if(tour){const elapsed=(now-tourStart)/1000;const next=Math.min(Math.floor(elapsed/6),world.cameras.length-1);if(next!==selected)shot(next);const s=world.cameras[selected];const t=(elapsed%6)/6;camera.position.set(s.position[0]+Math.sin(t*Math.PI)*.6,s.position[1],s.position[2]+Math.sin(t*Math.PI)*.25);if(elapsed>=world.cameras.length*6){tour=false;el('tour').textContent='Play camera tour';if(recording)recorder?.stop();}}controls.update();camera.position.y=Math.max(.4,camera.position.y);renderer.info.reset();composer.render();frames++;if(now-lastPerf>1000){fps=frames*1000/(now-lastPerf);frames=0;lastPerf=now;el('status').textContent=`${statusExtra} · ${fps.toFixed(0)} FPS · ${renderer.info.render.calls} draws`;}}
try{load(kind);requestAnimationFrame(animate);}catch(e){fail(e);}
